-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 03:04:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simpanpinjam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simpanpinjam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simpanpinjam` DEFAULT CHARACTER SET utf8 ;
USE `simpanpinjam` ;

-- -----------------------------------------------------
-- Table `simpanpinjam`.`anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`anggota` (
  `nik` VARCHAR(16) NOT NULL,
  `nama` VARCHAR(50) NULL,
  `ttl` VARCHAR(50) NULL,
  `golongan_darah` VARCHAR(2) NULL,
  `pekerjaan` VARCHAR(50) NULL,
  `alamat` VARCHAR(200) NULL,
  `email` VARCHAR(45) NULL,
  `no_telp` VARCHAR(60) NULL,
  `password` VARCHAR(100) NULL,
  `is_pengurus` TINYINT NULL,
  `is_aktif` TINYINT NULL,
  `tgl_aktif` DATETIME NULL,
  `is_stop` TINYINT NULL,
  PRIMARY KEY (`nik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`berkas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`berkas` (
  `id` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`tipe_simpanan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`tipe_simpanan` (
  `id` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`simpan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`simpan` (
  `id` VARCHAR(50) NOT NULL,
  `anggota_nik` VARCHAR(16) NOT NULL,
  `tipe_simpanan_id` INT NOT NULL,
  `tgl_transaksi` DATETIME NULL,
  `jumlah` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_simpan_anggota1_idx` (`anggota_nik` ASC),
  INDEX `fk_simpan_tipe_simpanan1_idx` (`tipe_simpanan_id` ASC),
  CONSTRAINT `fk_simpan_anggota1`
    FOREIGN KEY (`anggota_nik`)
    REFERENCES `simpanpinjam`.`anggota` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_simpan_tipe_simpanan1`
    FOREIGN KEY (`tipe_simpanan_id`)
    REFERENCES `simpanpinjam`.`tipe_simpanan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`tipe_pinjaman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`tipe_pinjaman` (
  `id` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`tipe_bunga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`tipe_bunga` (
  `id` INT NOT NULL,
  `nama` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`pinjam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`pinjam` (
  `id` VARCHAR(50) NOT NULL,
  `anggota_nik` VARCHAR(16) NOT NULL,
  `tipe_pinjaman_id` INT NOT NULL,
  `tipe_bunga_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pinjam_anggota1_idx` (`anggota_nik` ASC),
  INDEX `fk_pinjam_tipe_pinjaman1_idx` (`tipe_pinjaman_id` ASC),
  INDEX `fk_pinjam_tipe_bunga1_idx` (`tipe_bunga_id` ASC),
  CONSTRAINT `fk_pinjam_anggota1`
    FOREIGN KEY (`anggota_nik`)
    REFERENCES `simpanpinjam`.`anggota` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pinjam_tipe_pinjaman1`
    FOREIGN KEY (`tipe_pinjaman_id`)
    REFERENCES `simpanpinjam`.`tipe_pinjaman` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pinjam_tipe_bunga1`
    FOREIGN KEY (`tipe_bunga_id`)
    REFERENCES `simpanpinjam`.`tipe_bunga` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`angsuran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`angsuran` (
  `id` VARCHAR(50) NOT NULL,
  `pinjam_id` VARCHAR(50) NOT NULL,
  `tgl_transaksi` DATETIME NULL,
  `jumlah` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_angsuran_pinjam1_idx` (`pinjam_id` ASC),
  CONSTRAINT `fk_angsuran_pinjam1`
    FOREIGN KEY (`pinjam_id`)
    REFERENCES `simpanpinjam`.`pinjam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`ambil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`ambil` (
  `id` VARCHAR(50) NOT NULL,
  `anggota_nik` VARCHAR(16) NOT NULL,
  `tgl_transaksi` DATETIME NULL,
  `jumlah` INT NULL,
  `ambilcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ambil_anggota1_idx` (`anggota_nik` ASC),
  CONSTRAINT `fk_ambil_anggota1`
    FOREIGN KEY (`anggota_nik`)
    REFERENCES `simpanpinjam`.`anggota` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simpanpinjam`.`berkas_anggota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpanpinjam`.`berkas_anggota` (
  `anggota_nik` VARCHAR(16) NOT NULL,
  `berkas_id` INT NOT NULL,
  `tgl_diberikan` DATETIME NULL,
  PRIMARY KEY (`anggota_nik`, `berkas_id`),
  INDEX `fk_anggota_has_berkas_berkas1_idx` (`berkas_id` ASC),
  INDEX `fk_anggota_has_berkas_anggota1_idx` (`anggota_nik` ASC),
  CONSTRAINT `fk_anggota_has_berkas_anggota1`
    FOREIGN KEY (`anggota_nik`)
    REFERENCES `simpanpinjam`.`anggota` (`nik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_has_berkas_berkas1`
    FOREIGN KEY (`berkas_id`)
    REFERENCES `simpanpinjam`.`berkas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
